# Generated by Django 5.2.15 on 2026-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('quanity', models.PositiveIntegerField(verbose_name='Количество')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
