# Generated by Django 5.2.15 on 2026-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('shipped', 'Доставлен в службу доставки'), ('delivered', 'Доставлен')], default='new', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
